### ISSUE TITLE
Healthkit Emulator

### ISSUE THREAD

**Issue by leonfs** [mseemann/healthkit-sample-generator#2]
Hi,

First of all, thanks for the tool. 

How could you run this tool from XCode on the ios emulator to generate test data? I'm new to iOS development and I can't find a way to run the app on the emulator.  

When I try to load the example I end up getting: /healthkit-sample-generator/Example/HealthKitSampleGenerator/ProfilesTableViewController.swift:11:8: Cannot load underlying module for 'HealthKitSampleGenerator'

Regards,
Leo

**Comment by mseemann** [comment]
please have a look at the "Status" topic in the Readme.md. Until now it is only possible to export the health date and import them later.

This project uses CocoaPods. To get started with pods please have a look at https://guides.cocoapods.org/using/getting-started.html.

If you try to run the example directly you need to open the HealthKitSampleGenerator.xcworkspace not the HealthKitSampleGenerator.xcodeproj.
