### ISSUE TITLE
Xcode 7 built in simulated samples

### ISSUE THREAD

**Issue by tysun** [mseemann/healthkit-sample-generator#3]
Hi

I noticed that when I run my health app in the SIM it is auto-generating random HK data based on my HKQuantityType in my code. i.e. bpm, distance and energy. 

Is this a new feature of Xcode? Is your API different?

**Comment by mseemann** [comment]
Hi. The Code right now is only able to import Data that were Prozent previously exported. I have no idea why you see auto-generated data. May be you can ask your question at stackverflow...
